name: Package Excalibur with PyInstaller

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.config.os }}

    strategy:
      matrix:
        config:
          - { os: macos-latest, arch: x64, name: macos-latest }
          - { os: ubuntu-latest, arch: x64, name: ubuntu-latest }
          - { os: windows-latest, arch: x64, name: windows-latest }
          - { os: windows-latest, arch: ia32, name: windows-latest-32 }

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
      - name: Build with PyInstaller on Ubuntu and MacOS
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: |
          pyi-makespec --paths=excalibur/executors/celery_executor.py arthur.py
          pyinstaller --onefile --add-data "excalibur/www/templates:excalibur/www/templates" --add-data "excalibur/www/static:excalibur/www/static" --add-data "excalibur/config_templates:excalibur/config_templates" --name "excalibur-${{ matrix.config.os }}-${{ matrix.config.arch }}" arthur.py
      - name: Build with PyInstaller on Windows
        if: runner.os == 'Windows'
        run: |
          pyi-makespec --paths=excalibur/executors/celery_executor.py arthur.py
          pyinstaller --onefile --add-data "excalibur/www/templates;excalibur/www/templates" --add-data "excalibur/www/static;excalibur/www/static" --add-data "excalibur/config_templates;excalibur/config_templates" --name "excalibur-${{ matrix.config.os }}-${{ matrix.config.arch }}" arthur.py
      - name: Upload a build artifact
        uses: actions/upload-artifact@v1
        with:
          name: Builds
          path: dist/
